"""SMPC privacy mechanism via 2-party additive secret sharing.

Implements the PrivacyMechanism Protocol (privacy_ml.ppt.base).
Operates at the "embedding" layer (128-d vectors between encoder and head).

Two execution modes:
  - apply(): share-then-reconstruct simulation for the MIA pipeline. Output
    is numerically identical to input (lossless for linear ops).
  - secret_share(): exposes per-server input shares without reconstruction.
    Used by attacks/reconstruction.py to simulate a single-server-compromise
    adversary that observes only one server's share.

For inference the SMPCInferenceProtocol class implements a real 2-party
SMPC for a linear head y = W @ x + b. Both x AND (W, b) are additively
split across two servers; multiplication uses Beaver triples generated by
the client (trusted-dealer simulation). Server A's view consists only of
(W_A, b_A, x_A, opened masks d, e), all of which are uniformly random when
viewed in isolation; symmetrically for Server B.

Threat model: semi-honest, 2-party, static corruption, polynomial-time
adversary. Servers do not collude. See docs/superpowers/specs/2026-04-18-mia-design.md §2.
"""
from __future__ import annotations

import numpy as np

from .base import PPTLayer


class SecretShareSMPC:
    """Additive secret-sharing mechanism at the embedding layer.

    Splits each 128-d embedding into n_shares random additive shares
    that sum back to the original. apply() reconstructs and returns the
    original (lossless to float32 precision); secret_share() returns the
    raw per-server shares for adversary-view simulations.
    """

    layer: PPTLayer = "embedding"

    def __init__(self, n_shares: int, seed: int) -> None:
        if n_shares < 2:
            raise ValueError(f"n_shares must be >= 2, got {n_shares}")
        self._n_shares = n_shares
        self._rng = np.random.default_rng(seed)

    def fit(self, X: np.ndarray) -> None:
        return None

    def secret_share(self, X: np.ndarray) -> list[np.ndarray]:
        """Split X into n_shares additive shares.

        Returns a list of length n_shares whose elementwise sum equals X.
        Each individual share is uniform-random and reveals nothing about X
        (information-theoretic security under the non-collusion assumption).
        """
        X = np.asarray(X, dtype=np.float32)
        random_shares = [
            self._rng.standard_normal(X.shape).astype(np.float32)
            for _ in range(self._n_shares - 1)
        ]
        final_share = X - np.sum(random_shares, axis=0).astype(np.float32)
        return random_shares + [final_share]

    def apply(self, X: np.ndarray) -> np.ndarray:
        """Share-and-reconstruct each embedding row.

        Output is numerically identical to input (lossless for linear ops).
        """
        shares = self.secret_share(X)
        return np.sum(shares, axis=0).astype(np.float32)


class SMPCInferenceProtocol:
    """Real 2-party SMPC for a linear head: y = W @ x + b.

    Both input embeddings AND head weights/bias are additively split across
    two servers. Each server holds (W_i, b_i, x_i) for its index i.
    Multiplication of two additively-shared values uses Beaver triples
    generated by the client (trusted-dealer setup): functionally equivalent
    to standard 2-party Beaver SMPC.

    What each server sees on a single inference:
        Server A: W_A, b_A, x_A, a_A, u_A, c_A, opened (d, e)
        Server B: W_B, b_B, x_B, a_B, u_B, c_B, opened (d, e)
    All quantities above are uniformly random when viewed alone — the joint
    distribution of A's view is independent of (W, x).

    Output reconstruction is bit-equal to W @ x + b within float32 precision:
        W @ x + b = (W_A + W_B) @ (x_A + x_B) + (b_A + b_B)
    """

    def __init__(self, W: np.ndarray, b: np.ndarray, seed: int) -> None:
        W = np.asarray(W, dtype=np.float32)
        b = np.asarray(b, dtype=np.float32)
        self._rng = np.random.default_rng(seed)
        self._W_A = self._rng.standard_normal(W.shape).astype(np.float32)
        self._W_B = (W - self._W_A).astype(np.float32)
        self._b_A = self._rng.standard_normal(b.shape).astype(np.float32)
        self._b_B = (b - self._b_A).astype(np.float32)
        self._W_shape = W.shape

    def predict(self, X: np.ndarray) -> np.ndarray:
        """Run SMPC inference (linear part only) for a batch of embeddings."""
        X = np.asarray(X, dtype=np.float32)
        return np.stack([self._predict_one(x) for x in X], axis=0).astype(
            np.float32
        )

    def _predict_one(self, x: np.ndarray) -> np.ndarray:
        x_A = self._rng.standard_normal(x.shape).astype(np.float32)
        x_B = (x - x_A).astype(np.float32)

        a = self._rng.standard_normal(self._W_shape).astype(np.float32)
        u = self._rng.standard_normal(x.shape).astype(np.float32)
        c = (a @ u).astype(np.float32)
        a_A = self._rng.standard_normal(a.shape).astype(np.float32)
        a_B = (a - a_A).astype(np.float32)
        u_A = self._rng.standard_normal(u.shape).astype(np.float32)
        u_B = (u - u_A).astype(np.float32)
        c_A = self._rng.standard_normal(c.shape).astype(np.float32)
        c_B = (c - c_A).astype(np.float32)

        d_A = self._W_A - a_A
        d_B = self._W_B - a_B
        e_A = x_A - u_A
        e_B = x_B - u_B
        d = d_A + d_B
        e = e_A + e_B

        z_A = c_A + d @ u_A + a_A @ e + self._b_A
        z_B = c_B + d @ u_B + a_B @ e + d @ e + self._b_B
        return (z_A + z_B).astype(np.float32)
